<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/ionRangeSlider/css/ion.rangeSlider.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/ionRangeSlider/css/ion.rangeSlider.skinNice.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/password-indicator/css/password-indicator.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-combobox/css/bootstrap-combobox.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/jquery-tag-it/css/jquery.tagit.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/select2/dist/css/select2.min.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/jquery-simplecolorpicker/jquery.simplecolorpicker.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/jquery-simplecolorpicker/jquery.simplecolorpicker-fontawesome.css" rel="stylesheet" />
<link href="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/jquery-simplecolorpicker/jquery.simplecolorpicker-glyphicons.css" rel="stylesheet" />
<script src="{{ asset('/public/back/color_admin_v411') }}/assets/plugins/pace/pace.min.js"></script>